version: '3.8'
services:
  mecha-type-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mecha-type-api
    restart: always
    ports:
      - 4000:4000
    expose:
      - 4000
    depends_on:
      - mecha-type-db
    env_file:
      - .env

  mecha-type-db:
    image: postgres:13
    container_name: mecha-type-db
    restart: always
    ports:
      - '5432:5432'
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-prisma-docker-db
