version: '3.8'
services:
  gardentify-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gardentify-server
    restart: always
    ports:
      - 4000:4000
    expose:
      - 4000
    depends_on:
      - gardentify-server-db
    env_file:
      - .env

  gardentify-server-db:
    image: postgres:13
    container_name: gardentify-server-db
    restart: always
    ports:
      - '5432:5432'
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: gardentify-server
