import { PlantType as PrismaType } from '@prisma/client';
import { PlantType } from '../modules/user-plants/models/user-plant.model';

/**
 *
 * @param plant plant type generated by PrismaJS.
 * @returns the parsed plant based on the model we created.
 */
export const parsePlantType = (type: PrismaType): PlantType => {
  let parsedType: PlantType = PlantType.NONE;

  // Parse enum type to the one in the plant model.
  Object.values(PlantType).forEach((stype: string) => {
    if (type === stype) {
      parsedType = stype as PlantType;
    }
  });

  return parsedType;
};
